### ISSUE TITLE
Ansible to Helm

### ISSUE THREAD

**Issue by jpopelka** [packit/deployment#419]
[Helm will be the cornerstone of our nextgen Continuous Deployment](https://github.com/packit/deployment/issues/382#issuecomment-1341328072)

- [ ] Helmize our deployment
  - [ ] packit/helm#13
  - [ ] packit/helm#14
  - [ ] Add the rest of the resources to the Helm chart & CD
  - [ ] Deliver a Helm demo to the team 😇
- [ ] Research whether [Kustomize](https://kustomize.io) would help us in any way?
- [ ] Research whether [ArgoCD](https://issues.redhat.com/browse/PACKIT-1998) would help us in any way?

**Comment by jpopelka** [comment]
- What's the benefit?
  - standard way of deploying an k8s application
- Who will benefit?
  - us

**Comment by lachmanfrantisek** [comment]
After a team discussion, we didn't pick this as a top Packit team priority for the next quarter and preferred epics with bigger user benefits. (Sadly, we have limited resources...)

**Comment by nforro** [comment]
We will probably never get to implementing this. There are other more important related issues.
