### ISSUE TITLE
Managed Platform Plus

### ISSUE THREAD

**Issue by jpopelka** [packit/deployment#425]
(all links are RH internal)

Managed Platform Plus (MP+) is RH's OCP (OpenShift v4) based hosting platform. There are lots of [constraints](https://source.redhat.com/groups/public/itpaas/managedplatformplushub/mppluswiki/is_mp_the_right_place_to_host_your_application) & standards we need to adhere to if we want to run Packit (Service) there. This issue lists them so that we have them in mind and gradually work on them so that it's not overwhelming if we have to suddenly switch to MP+.

- [ ] [Enterprise Security Standard (ESS)](https://source.redhat.com/departments/it/it-information-security/wiki/enterprise_security_standard_80_essv8) (I'm not entirely sure which of the requirements apply to us, but I have this list):
    - [ ] SEC-APP-REQ-1 (Secure Application Development) - Implement Input/Output Validation & Secure Session Management
    - [ ] SEC-APP-REQ-2 (Static Application Security Testing - SAST) - Remediate High/Medium risk vulnerabilities from static code analysis (SonarQube)
    - [ ] SEC-APP-REQ-4 (Remediate Vulnerable Libraries) - Run tools like OWASP Dependency Check or Snyk & remediate vulnerabilities with CVSS > 4.0
    - [ ] SEC-CONFIG-REQ1 (Hardening or Security Configuration of OS)
      - [ ] Use a minimum amount of packages/modules/services
    - [ ] SEC-CONFIG-REQ-2 (Secure Password Management)
      - [ ] Change vendor-supplied default admin credentials (userid/passwords) before an application/system is deployed in production
      - [ ] Comply with InfoSec operating guidelines around storing and sharing system-level passwords
    - [ ] SEC-CONFIG-REQ-4 (WAF - Web Application Firewall) - Deploy WAF to detect & prevent web-based attacks
    - [ ] SEC-CONFIG-REQ-9 (Configuration Management) - Have CMDB record(s) updated
    - [ ] SEC-PATCH-REQ-1 (Application Patching) - All vendor-released Security Patches (Application Level) must be applied or deployed in production at the earliest
    - [ ] SEC-PATCH-REQ-2 (OS Patching)
      - [ ] Use the latest major OS release
      - [ ] All OS security patches (or updates) must be applied on prod systems at the earliest
    - [ ] SEC-ACC-REQ-13 (Authorization) - Enforcing Principle of Least Privilege when providing access to any sensitive functionality - follow InfoSec & IAM Guidance
    - [ ] SEC-PKI-REQ-1 (Secure Certificate Mgmt) - e.g. don't use wildcard certs
    - [ ] SEC-CHG-REQ-1 (Change Management) - Follow the Change Management process and procedures, as applicable/appropriate
- [ ] Be ready to accept responsibility for building applications, managing CI/CD pipelines, and supporting applications.
- [ ] Use the [MP+ Image Lifecycle](https://source.redhat.com/departments/it/digitalsolutionsdelivery/it-application-lifecycle-management/old_wiki/enterprise_alm_standards), immutable image standards, and related CI/CD tools to ensure security, resiliency, and operability
    - [ ] ALM-BUILD-1: Secure Build Environments - Application artifacts must be built on systems and services that meet enterprise security standards
    - [ ] ALM-BUILD-2: Certifed Base Images - All container images built must be based on or built with in the case of S2I, Red Hat images that are certified, supported, and updated.
    - [ ] ALM-DISTRIBUTION-1: Secure Artifact Distribution - Application artifacts must be stored on and distributed through services that meet enterprise security standards and have business continuity plans.
- [ ] Resiliency and high availability
    - [ ] At least 2 pod replicas
    - [ ] Liveness & readiness probes
- [x] Managing resource requests & limits
- [ ] Tag resources

**Comment by TomasTomecek** [comment]
> ALM-BUILD-2: Certifed Base Images - All container images built must be based on or built with in the case of S2I, Red Hat images that are certified, supported, and updated.

huh, this is a big one
