### ISSUE TITLE
Firewall rules that need to be enabled

### ISSUE THREAD

**Issue by mfocko** [packit/deployment#575]
This issue is for tracking the domains that have been discovered **not to** work on MP+.

### TODO

- [x] Request the firewall rules to be set
- [x] Verify they work
- [x] Clone the issue for new “waiting list”
   - #593

### Waiting list

* `codeberg.org` (suggested in the Matrix chat)
* `.kernel.org` (requested by @nforro for the manpages + kexec-tools + btrfs-progs)
* `cran.r-project.org` (by @lbarcziova for packit/packit-service#2278)
* `git.dpkg.org`  (by @lbarcziova for packit/packit-service#2398)

### Additional domains from the specfile research

* `.kde.org` (for both archives and potential Invent KDE git forge integration)
* `.xfce.org` (for potential onboarding of packages)
* `.qt.io` (related to the Invent KDE integration)
* `x.org` (quantity of packages)
* `ctan.math.illinois.edu` (quantity of packages; LaTeX, expecting not many patches)
* `hackage.haskell.org` (relatively big quantity of packages)

**Comment by mfocko** [comment]
### Current waiting list

* `codeberg.org` (suggested in the Matrix chat)
* `.kernel.org` (requested by @nforro for the manpages)
* `cran.r-project.org` (by @lbarcziova for packit/packit-service#2398)

**Comment by mfocko** [comment]
Ticket has been created.
