### ISSUE TITLE
Missing firewall rules, pt. 2

### ISSUE THREAD

**Issue by mfocko** [packit/deployment#593]
Issue for tracking the domains that have been discovered **not to** work on MP+.

### TODO

- [x] Request the firewall rules to be set
- [x] Verify they work
- [ ] Clone the issue for the next “waiting list”

### Waiting list

* https://imagemagick.org (by @lbarcziova for https://src.fedoraproject.org/rpms/ImageMagick/pull-request/13)
* libarchive.org (by @lbarcziova for https://dashboard.packit.dev/jobs/pull-from-upstream/10913)

### Notes

This is a tracking issue for any domains that are not allowed on the firewall and are blocking onboarding of Packit or Packit integration with an upstream forge. To not make the waiting requests “rot” in the backlog, there is a monthly deadline, in case there are no rules to be enabled, just shift the deadline by one more month, otherwise open a ticket to the IT to set the firewall rules.

### How to request the firewall rules

See [here](https://packit.dev/deployment/specifics/clusters#firewall)

**Comment by mfocko** [comment]
Opened RITM1897456

**Comment by mfocko** [comment]
Verfied. Works.
