### ISSUE TITLE
Missing firewall rules, pt. 3

### ISSUE THREAD

**Issue by mfocko** [packit/deployment#600]
Issue for tracking the domains that have been discovered **not to** work on MP+.

### TODO

- [x] Request the firewall rules to be set
- [x] Verify they work
- [x] Clone the issue for the next “waiting list”

### Waiting list

* download.nextcloud.com (by @lbarcziova for https://github.com/packit/packit-service/issues/2398 - https://dashboard.packit.dev/jobs/pull-from-upstream/11836)
* breakfastquay.com ( for https://dashboard.packit.dev/jobs/pull-from-upstream/12314)
* kornelix.net (for https://dashboard.packit.dev/jobs/pull-from-upstream/13414)

### Notes

This is a tracking issue for any domains that are not allowed on the firewall
and are blocking onboarding of Packit or Packit integration with an upstream
forge. To not make the waiting requests “rot” in the backlog, there is a monthly
deadline, in case there are no rules to be enabled, just shift the deadline by
one more month, otherwise open a ticket to the IT to set the firewall rules.

### How to request the firewall rules

See [here](https://packit.dev/deployment/specifics/clusters#firewall)

**Comment by lbarcziova** [comment]
Opened RITM1984201.

**Comment by lbarcziova** [comment]
Firewall rules are applied.
